package com.EventHorizon.homeschoolr;

public enum TaskName {
    AUTH_CREATE_USER_SUCCESSFUL,
    AUTH_DELETE_USER,
    AUTH_RESET_PASSWORD_SENDING,
    AUTH_SIGN_IN_SUCCESSFUL,
    AUTH_DELETE_ACCOUNT_SUCCESSFUL,

    DB_DELETE_USER,
    DB_GET_FAMILY_NAME,
    DB_GET_USER_ID,
    DB_GET_FAMILY_ID,
    DB_CREATE_USER_AND_FAMILY,
    DB_GET_USER_NAME,
    DB_INVITE_MEMBER,

    DB_FAMILY_NAME_DOES_NOT_EXIST,
    DB_FAMILY_LOADED_SUCCESSFULLY,
    DB_FAMILY_DOES_NOT_EXIST
}
